name: frontend
description: Synk - Real-time Chat Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  socket_io_client: ^2.0.3+1
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
